import type { Product } from "./api";

/**
 * Mocks alinhados ao schema do backend (Products.js).
 * Imagens são placeholders coloridos via picsum.photos para uma vibe densa estilo Steam.
 */

const img = (seed: string, w = 800, h = 1000) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const mockProducts: Product[] = [
  {
    _id: "p001",
    nameOfProduct: "Console Retro Arcade 16-bit",
    priceOfProduct: 1299.9,
    amount: 12,
    description:
      "Console all-in-one com 200 jogos clássicos pré-instalados, dois controles e saída HDMI 1080p.",
    available: true,
    category: ["Video Games", "Retro"],
    observations: "Edição limitada — caixa colecionável",
    main: true,
    image: img("retro-console"),
  },
  {
    _id: "p002",
    nameOfProduct: "Headset Gamer Nebula Pro",
    priceOfProduct: 549.0,
    amount: 30,
    description: "Som surround 7.1, RGB sincronizado e microfone com cancelamento de ruído.",
    available: true,
    category: ["Acessórios", "Video Games"],
    observations: "Compatível com PC, PS5 e Xbox Series",
    main: true,
    image: img("headset-rgb"),
  },
  {
    _id: "p003",
    nameOfProduct: "HQ — Cavaleiros do Infinito Vol.1",
    priceOfProduct: 89.9,
    amount: 45,
    description: "Edição encadernada capa dura, 320 páginas, papel couché.",
    available: true,
    category: ["HQs"],
    observations: "Tradução oficial revisada",
    main: false,
    image: img("hq-knights"),
  },
  {
    _id: "p004",
    nameOfProduct: "Funko Colecionável Dragão Vermelho",
    priceOfProduct: 159.9,
    amount: 8,
    description: "Figura colecionável de 12cm com base iluminada por LED.",
    available: true,
    category: ["Colecionáveis"],
    observations: "Lote raro — apenas 8 unidades",
    main: false,
    image: img("funko-dragon"),
  },
  {
    _id: "p005",
    nameOfProduct: "Camiseta Pixel Quest",
    priceOfProduct: 99.9,
    amount: 60,
    description: "Algodão pima, estampa serigráfica resistente a lavagens.",
    available: true,
    category: ["Roupas Temáticas"],
    observations: "Tamanhos P ao GG",
    main: false,
    image: img("tshirt-pixel"),
  },
  {
    _id: "p006",
    nameOfProduct: "Jogo de Tabuleiro — Galáxia Caída",
    priceOfProduct: 329.0,
    amount: 18,
    description: "Estratégia 4X para 2 a 5 jogadores. Partidas de 90–180 min.",
    available: true,
    category: ["Jogos", "Tabuleiro"],
    observations: "Premiado: Melhor Estratégia 2025",
    main: true,
    image: img("board-galaxy"),
  },
  {
    _id: "p007",
    nameOfProduct: "Mousepad RGB Infinity 90cm",
    priceOfProduct: 249.0,
    amount: 25,
    description: "Superfície de tecido tratado, base antiderrapante e borda iluminada.",
    available: true,
    category: ["Acessórios"],
    observations: "USB-C com controle on-board",
    main: false,
    image: img("mousepad-rgb"),
  },
  {
    _id: "p008",
    nameOfProduct: "Estátua Cavaleiro Élfico 1/6",
    priceOfProduct: 1899.0,
    amount: 4,
    description: "Resina pintada à mão, 32cm de altura, com certificado de autenticidade.",
    available: true,
    category: ["Colecionáveis"],
    observations: "Edição numerada 1/250",
    main: true,
    image: img("statue-elf"),
  },
  {
    _id: "p009",
    nameOfProduct: "Moletom Capuz Pixel Skull",
    priceOfProduct: 219.0,
    amount: 22,
    description: "Moletom flanelado com bolso canguru e estampa silk premium.",
    available: true,
    category: ["Roupas Temáticas"],
    observations: "Disponível em preto e cinza",
    main: false,
    image: img("hoodie-skull"),
  },
  {
    _id: "p010",
    nameOfProduct: "Box HQ — Era das Sombras (5 vol.)",
    priceOfProduct: 349.9,
    amount: 10,
    description: "Caixa com 5 volumes, marcador exclusivo e pôster.",
    available: true,
    category: ["HQs"],
    observations: "Estoque limitado",
    main: true,
    image: img("hq-box"),
  },
  {
    _id: "p011",
    nameOfProduct: "Controle Pro Wireless Hex",
    priceOfProduct: 449.0,
    amount: 0,
    description: "Controle profissional com gatilhos hall effect e bateria de 40h.",
    available: false,
    category: ["Acessórios", "Video Games"],
    observations: "Esgotado — reposição em breve",
    main: false,
    image: img("controller-pro"),
  },
  {
    _id: "p012",
    nameOfProduct: "Card Game — Duelo Arcano",
    priceOfProduct: 79.9,
    amount: 50,
    description: "Deck inicial com 60 cartas + manual ilustrado.",
    available: true,
    category: ["Jogos"],
    observations: "2 jogadores, 20 min por partida",
    main: false,
    image: img("cardgame-arcane"),
  },
];

export const allCategories = Array.from(
  new Set(mockProducts.flatMap((p) => p.category)),
).sort();
